# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://hobit.com.ar
title: HOB-IT
email: info@hob-it.com.ar
author: HOB-IT
description: HOB-IT. Making IT awesome!

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/HOB-IT
#  - title: linkedin
#    url:
  - title: facebook
    url: https://www.facebook.com/hobit.arg
#  - title: twitter
#    url: https://twitter.com/SBootstrap
